version: "3.6"
services:
  app:
    build:
      context: .
      args:
        DEBUG: ${DEBUG}
        NODE_ENV: development
    command: npm run start:dev
    container_name: sous-chef-ssr-dev
    env_file: .env
    ports:
      - "3000:80"
      # Node debug ports
      - "9229:9229"
    volumes:
      - "./@types:/opt/app/@types"
      - "./src:/opt/app/src"
